CREATE DATABASE IF NOT EXISTS Motos
DEFAULT CHARACTER SET utf8 
DEFAULT COLLATE utf8_general_ci;

USE Motos;

DROP TABLE IF EXISTS Motos;

CREATE TABLE MOTOS( 
NUMERO INT PRIMARY KEY,
MARCA VARCHAR(50),
MODELO VARCHAR(50)
);
